### ISSUE TITLE
[FEATURE] Optionally track sites by path

### ISSUE THREAD

**Issue by quantimnot** [sheepzh/timer#191]
Hello, I'm looking for a way to track my time on sites like github.com. I would like to know how much time I'm spending on individual repositories than for "GitHub." How much time at `github.com/sheepzh/timer` compared to `github.com/nim-lang/nim`.

**Comment by sheepzh** [comment]
Thanks for your submission~

Coincidentally, I have designed and am developping one feture to satisfy your request, #186 .

After this published, you can create one visual site with customized ant pattern of path, such as `github.com/sheepzh/*` `github.com/**` to track time of every path you want to know.

The original issue is discussed in Chinese, I will sync process in this one.

**Comment by sheepzh** [comment]
Hi, the above feature is mostly developped, and will be released in v1.6.0 in serveral days, because some tests need to be done.

Then you can create virtual sites with host rules, such as `github.com/nim-lang/nim` and `github.com/sheepzh/timer`

![image](https://user-images.githubusercontent.com/19428473/224690405-fbc6c691-ac91-42d2-89f3-fabcd66fe4dc.png)

And compare them on the report page

![image](https://user-images.githubusercontent.com/19428473/224691090-bb047e6b-6212-497f-a4c5-79f0f6b498e8.png)
